import {detectWebp} from './detect-webp';
import {initFixedHeader} from './fixed-header';
import {initMenu} from './menu';
import {initPromoSlider} from './promo-slider';
import {initToursSlider} from './tours-slider';
import {initTrainingSlider} from './training-slider';
import {initReviewsSlider} from './reviews-slider';
import {initAdvantagesSlider} from './advantages-slider';
import {initGallerySlider} from './gallery-slider';
import {initForm} from './form';

detectWebp();
initFixedHeader();
initMenu();
initPromoSlider();
initToursSlider();
initTrainingSlider();
initReviewsSlider();
initAdvantagesSlider();
initGallerySlider();
initForm();
